from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.graphs_layout = QtWidgets.QGridLayout()
        self.graphs_layout.setObjectName("graphs_layout")

        self.original_graph_label = QtWidgets.QLabel(self.centralwidget)
        self.original_graph_label.setObjectName("original_graph_label")
        self.graphs_layout.addWidget(self.original_graph_label, 0, 0, 1, 1)

        self.original_spectrogram_label = QtWidgets.QLabel(self.centralwidget)
        self.original_spectrogram_label.setObjectName("original_spectrogram_label")
        self.graphs_layout.addWidget(self.original_spectrogram_label, 0, 2, 1, 1)

        self.equalized_graph = QtWidgets.QGraphicsView(self.centralwidget)
        self.equalized_graph.setObjectName("equalized_graph")
        self.graphs_layout.addWidget(self.equalized_graph, 4, 0, 1, 1)

        self.original_graph = QtWidgets.QGraphicsView(self.centralwidget)
        self.original_graph.setObjectName("original_graph")
        self.graphs_layout.addWidget(self.original_graph, 1, 0, 1, 1)

        self.original_spectrogram = QtWidgets.QGraphicsView(self.centralwidget)
        self.original_spectrogram.setObjectName("original_spectrogram")
        self.graphs_layout.addWidget(self.original_spectrogram, 1, 2, 1, 1)

        self.equalized_graph_label = QtWidgets.QLabel(self.centralwidget)
        self.equalized_graph_label.setObjectName("equalized_graph_label")
        self.graphs_layout.addWidget(self.equalized_graph_label, 2, 0, 1, 1)

        self.equalized_spectrogram = QtWidgets.QGraphicsView(self.centralwidget)
        self.equalized_spectrogram.setObjectName("equalized_spectrogram")
        self.graphs_layout.addWidget(self.equalized_spectrogram, 4, 2, 1, 1)

        self.equalized_spectrogram_label = QtWidgets.QLabel(self.centralwidget)
        self.equalized_spectrogram_label.setObjectName("equalized_spectrogram_label")
        self.graphs_layout.addWidget(self.equalized_spectrogram_label, 2, 2, 1, 1)

        self.gridLayout.addLayout(self.graphs_layout, 0, 1, 1, 1)

        self.frequency_plot_layout_2 = QtWidgets.QGridLayout()
        self.frequency_plot_layout_2.setObjectName("frequency_plot_layout_2")

        self.frequency_scale_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.frequency_scale_label_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frequency_scale_label_2.setObjectName("frequency_scale_label_2")
        self.frequency_plot_layout_2.addWidget(self.frequency_scale_label_2, 0, 1, 1, 1)

        self.frequency_plot_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.frequency_plot_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frequency_plot_2.setObjectName("frequency_plot_2")
        self.frequency_plot_layout_2.addWidget(self.frequency_plot_2, 1, 1, 1, 1)

        self.sliders_layout = QtWidgets.QGridLayout()
        self.sliders_layout.setObjectName("sliders_layout")

        self.slider_7_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_7_label.setObjectName("slider_7_label")
        self.sliders_layout.addWidget(self.slider_7_label, 1, 3, 1, 1)

        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.sliders_layout.addWidget(self.verticalSlider_2, 0, 8, 1, 1)
        self.slider_4_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_4_label.setObjectName("slider_4_label")
        self.sliders_layout.addWidget(self.slider_4_label, 1, 6, 1, 1)
        self.slider_5_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_5_label.setObjectName("slider_5_label")
        self.sliders_layout.addWidget(self.slider_5_label, 1, 5, 1, 1)
        self.slider_6_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_6_label.setObjectName("slider_6_label")
        self.sliders_layout.addWidget(self.slider_6_label, 1, 4, 1, 1)
        self.slider_9_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_9_label.setObjectName("slider_9_label")
        self.sliders_layout.addWidget(self.slider_9_label, 1, 1, 1, 1)
        self.verticalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.sliders_layout.addWidget(self.verticalSlider_4, 0, 6, 1, 1)
        self.verticalSlider_10 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.sliders_layout.addWidget(self.verticalSlider_10, 0, 0, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.sliders_layout.addWidget(self.verticalSlider, 0, 9, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.sliders_layout.addWidget(self.verticalSlider_3, 0, 7, 1, 1)
        self.slider_8_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_8_label.setObjectName("slider_8_label")
        self.sliders_layout.addWidget(self.slider_8_label, 1, 2, 1, 1)
        self.verticalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.sliders_layout.addWidget(self.verticalSlider_7, 0, 3, 1, 1)
        self.slider_10_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_10_label.setObjectName("slider_10_label")
        self.sliders_layout.addWidget(self.slider_10_label, 1, 0, 1, 1)
        self.verticalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.sliders_layout.addWidget(self.verticalSlider_8, 0, 2, 1, 1)
        self.slider_1_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_1_label.setObjectName("slider_1_label")
        self.sliders_layout.addWidget(self.slider_1_label, 1, 9, 1, 1)
        self.slider_3_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_3_label.setObjectName("slider_3_label")
        self.sliders_layout.addWidget(self.slider_3_label, 1, 7, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.sliders_layout.addWidget(self.verticalSlider_6, 0, 4, 1, 1)
        self.slider_2_label = QtWidgets.QLabel(self.centralwidget)
        self.slider_2_label.setObjectName("slider_2_label")
        self.sliders_layout.addWidget(self.slider_2_label, 1, 8, 1, 1)
        self.verticalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.sliders_layout.addWidget(self.verticalSlider_5, 0, 5, 1, 1)
        self.verticalSlider_9 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.sliders_layout.addWidget(self.verticalSlider_9, 0, 1, 1, 1)

        self.frequency_plot_layout_2.addLayout(self.sliders_layout, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.frequency_plot_layout_2, 2, 1, 1, 1)

        self.graph_buttons_layout = QtWidgets.QHBoxLayout()
        self.graph_buttons_layout.setObjectName("graph_buttons_layout")

        self.play_pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause_button.setObjectName("play_pause_button")
        self.graph_buttons_layout.addWidget(self.play_pause_button)

        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setObjectName("reset_button")
        self.graph_buttons_layout.addWidget(self.reset_button)

        self.zoom_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.graph_buttons_layout.addWidget(self.zoom_in_button)

        self.zoom_out_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out_button.setObjectName("zoom_out_button")
        self.graph_buttons_layout.addWidget(self.zoom_out_button)

        self.speed_down_button = QtWidgets.QPushButton(self.centralwidget)
        self.speed_down_button.setObjectName("speed_down_button")
        self.graph_buttons_layout.addWidget(self.speed_down_button)

        self.speed_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.speed_up_button.setObjectName("speed_up_button")
        self.graph_buttons_layout.addWidget(self.speed_up_button)

        self.gridLayout.addLayout(self.graph_buttons_layout, 1, 1, 1, 1)

        self.controls_layout = QtWidgets.QVBoxLayout()
        self.controls_layout.setObjectName("controls_layout")

        self.file_name_label = QtWidgets.QLabel(self.centralwidget)
        self.file_name_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.file_name_label.setObjectName("file_name_label")
        self.controls_layout.addWidget(self.file_name_label)

        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setObjectName("load_button")
        self.controls_layout.addWidget(self.load_button)

        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.controls_layout.addWidget(self.save_button)

        self.choose_mode_label = QtWidgets.QLabel(self.centralwidget)
        self.choose_mode_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.choose_mode_label.setObjectName("choose_mode_label")
        self.controls_layout.addWidget(self.choose_mode_label)

        self.modes_checkbox = QtWidgets.QComboBox(self.centralwidget)
        self.modes_checkbox.setObjectName("modes_checkbox")
        self.controls_layout.addWidget(self.modes_checkbox)

        self.spectrogram_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.spectrogram_checkbox.setObjectName("spectrogram_checkbox")
        self.controls_layout.addWidget(self.spectrogram_checkbox)

        self.choose_frequency_scale_label = QtWidgets.QLabel(self.centralwidget)
        self.choose_frequency_scale_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.choose_frequency_scale_label.setObjectName("choose_frequency_scale_label")
        self.controls_layout.addWidget(self.choose_frequency_scale_label)

        self.linear_scale_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.linear_scale_radio_button.setObjectName("linear_scale_radio_button")
        self.controls_layout.addWidget(self.linear_scale_radio_button)

        self.auduigram_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.auduigram_radio_button.setObjectName("auduigram_radio_button")
        self.controls_layout.addWidget(self.auduigram_radio_button)

        self.gridLayout.addLayout(self.controls_layout, 0, 0, 2, 1)

        self.player_layout = QtWidgets.QVBoxLayout()
        self.player_layout.setObjectName("player_layout")
        self.player_1_placeholder = QtWidgets.QPushButton(self.centralwidget)
        self.player_1_placeholder.setObjectName("player_1_placeholder")
        self.player_layout.addWidget(self.player_1_placeholder)
        self.player_2_placeholder = QtWidgets.QPushButton(self.centralwidget)
        self.player_2_placeholder.setObjectName("player_2_placeholder")
        self.player_layout.addWidget(self.player_2_placeholder)
        self.gridLayout.addLayout(self.player_layout, 2, 0, 1, 1)

        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.original_graph_label.setText(_translate("MainWindow", "TextLabel"))
        self.original_spectrogram_label.setText(_translate("MainWindow", "TextLabel"))
        self.equalized_graph_label.setText(_translate("MainWindow", "TextLabel"))
        self.equalized_spectrogram_label.setText(_translate("MainWindow", "TextLabel"))
        self.frequency_scale_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.slider_7_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_4_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_5_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_6_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_9_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_8_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_10_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_1_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_3_label.setText(_translate("MainWindow", "TextLabel"))
        self.slider_2_label.setText(_translate("MainWindow", "TextLabel"))
        self.play_pause_button.setText(_translate("MainWindow", "PushButton"))
        self.reset_button.setText(_translate("MainWindow", "PushButton"))
        self.zoom_in_button.setText(_translate("MainWindow", "PushButton"))
        self.zoom_out_button.setText(_translate("MainWindow", "PushButton"))
        self.speed_down_button.setText(_translate("MainWindow", "PushButton"))
        self.speed_up_button.setText(_translate("MainWindow", "PushButton"))
        self.file_name_label.setText(_translate("MainWindow", "TextLabel"))
        self.load_button.setText(_translate("MainWindow", "PushButton"))
        self.save_button.setText(_translate("MainWindow", "PushButton"))
        self.choose_mode_label.setText(_translate("MainWindow", "TextLabel"))
        self.spectrogram_checkbox.setText(_translate("MainWindow", "CheckBox"))
        self.choose_frequency_scale_label.setText(_translate("MainWindow", "TextLabel"))
        self.linear_scale_radio_button.setText(_translate("MainWindow", "RadioButton"))
        self.auduigram_radio_button.setText(_translate("MainWindow", "RadioButton"))
        self.player_1_placeholder.setText(_translate("MainWindow", "PushButton"))
        self.player_2_placeholder.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
